### PR TITLE
rename old readme, create HCI readme

### PR DESCRIPTION
**Pull request by peter-gy**
@michalrzak, @memoriesadrift this pull request addresses #68 and it is based on the [template provided by the HCI team](http://vda.univie.ac.at/Teaching/HCI/21s/materials/README_M3.md). How would you enhance it?

### CODE REVIEW

**Review by michalrzak — APPROVED** [review]
I think it looks good. It may be worth considering if we don't want a a bit more detailed README for the github repo, as that could contain more information about the project. (e.g. link to the actual u:find, description of the project, etc...),

For now I think this README is enough.

**Comment by peter-gy** [comment]
Maybe we could also create a `submission` branch with this README and the `main` branch could have a more detailed README as you described.

**Comment by michalrzak** [comment]
Sounds like a good solution.

**Comment by memoriesadrift** [comment]
I don't think we need a more detailed readme at all, this HCI readme should suffice.

**Review by memoriesadrift — APPROVED** [review]

**Pull request merged**
