### PR TITLE
Advanced Search Screen Implemntation 

### PR DESCRIPTION
**Pull request by michalrzak**

### CODE REVIEW

**Comment by michalrzak** [comment]
Need help finding the best way to retrieve information from the SemesterInput after the user conducts a search.

**Comment by peter-gy** [comment]
The problem would be solved if you could retrieve the value of the text field and the dropdown at any point of time. Getting the value of the text field can be done as demonstrated here: https://flutter.dev/docs/cookbook/forms/retrieve-input

The articles I found about the DropDown all use a stateful widget and update a state variable whenever the value is changed.

**Comment by michalrzak** [comment]
I have solved this by creating a custom class that extends `TextEditingController` and allows me to access all properties of `SemesterInput`

**Comment by michalrzak** [comment]
@memoriesadrift @peter-gy Please pull this branch and check the **functionality** of the advance search screen. I know the UI is still rough. I am currently working on fixing that.

**Comment by peter-gy** [comment]
I tested it and functionally it works nicely (and I think the visuals are fairly ok as well) 2 enhancements that I would recommend:
- disable the Year controls if `Only current term` is checked
- when there are no course results, let's display a line of text, like `No results were found`

The only thing I find generally confusing is that the date of a course is not displayed.

**Comment by michalrzak** [comment]
> The only thing I find generally confusing is that the date of a course is not displayed.

This should be already fixed in main by @memoriesadrift .

Other then that I will try implement the suggestions. Thanks

**Comment by michalrzak** [comment]
@peter-gy @memoriesadrift I would also appreciate some suggestions how this advance search screen should be accessed. My best idea rn is to have tabs (Home & Advanced Search) at the bottom of the screen but I am open for suggestions and your opinions.

**Comment by memoriesadrift** [comment]
Why tabs, just add a button like the course directory, maybe even on the same row and just have it there to be tapped

**Comment by michalrzak** [comment]
> Why tabs, just add a button like the course directory, maybe even on the same row and just have it there to be tapped

Wouldn't that take up too much space? Especially if you have some favorites saved. And to me it also feels a bit like it should not have the same weight as the course directory.

**Comment by memoriesadrift** [comment]
> 
> 
> > Why tabs, just add a button like the course directory, maybe even on the same row and just have it there to be tapped
> 
> Wouldn't that take up too much space? Especially if you have some favorites saved. And to me it also feels a bit like it should not have the same weight as the course directory.

IMO better than introducing an additional UI element in tabs.  As for the weight, that's up to you

**Comment by michalrzak** [comment]
Ready to merge. In the end I added a button next to the course directory and decided not to overthink this.

**Pull request merged**
